/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class su_eqx_singasteinn_NativeScaler */

#ifndef _Included_su_eqx_singasteinn_NativeScaler
#define _Included_su_eqx_singasteinn_NativeScaler
#ifdef __cplusplus
extern "C" {
#endif
#undef su_eqx_singasteinn_NativeScaler_BUFFER_SIZE
#define su_eqx_singasteinn_NativeScaler_BUFFER_SIZE 20480L
/*
 * Class:     su_eqx_singasteinn_NativeScaler
 * Method:    init
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_su_eqx_singasteinn_NativeScaler_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     su_eqx_singasteinn_NativeScaler
 * Method:    receiveSamples
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_NativeScaler_receiveSamples
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     su_eqx_singasteinn_NativeScaler
 * Method:    availableSamples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_NativeScaler_availableSamples
  (JNIEnv *, jobject, jlong);

/*
 * Class:     su_eqx_singasteinn_NativeScaler
 * Method:    putSamples
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_NativeScaler_putSamples
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     su_eqx_singasteinn_NativeScaler
 * Method:    setRate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_su_eqx_singasteinn_NativeScaler_setRate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     su_eqx_singasteinn_NativeScaler
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_su_eqx_singasteinn_NativeScaler_delete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
