/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class su_eqx_singasteinn_MpegDecoder */

#ifndef _Included_su_eqx_singasteinn_MpegDecoder
#define _Included_su_eqx_singasteinn_MpegDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     su_eqx_singasteinn_MpegDecoder
 * Method:    _init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_su_eqx_singasteinn_MpegDecoder__1init
  (JNIEnv *, jclass);

/*
 * Class:     su_eqx_singasteinn_MpegDecoder
 * Method:    _getformat
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_MpegDecoder__1getformat
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     su_eqx_singasteinn_MpegDecoder
 * Method:    _open
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_MpegDecoder__1open
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     su_eqx_singasteinn_MpegDecoder
 * Method:    _close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_MpegDecoder__1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     su_eqx_singasteinn_MpegDecoder
 * Method:    _read
 * Signature: (J[B[I)I
 */
JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_MpegDecoder__1read
  (JNIEnv *, jclass, jlong, jintArray, jintArray);

JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_MpegDecoder__1delete
  (JNIEnv *, jclass, jlong ptr);

JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_MpegDecoder__1tell
  (JNIEnv *, jclass, jlong ptr);

JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_MpegDecoder__1length
  (JNIEnv *, jclass, jlong ptr);

JNIEXPORT jint JNICALL Java_su_eqx_singasteinn_MpegDecoder__1seek
  (JNIEnv *, jclass, jlong ptr, jint sample);

JNIEXPORT jstring JNICALL Java_su_eqx_singasteinn_MpegDecoder__1strerror
  (JNIEnv * env, jclass, jlong ptr);

JNIEXPORT jstring JNICALL Java_su_eqx_singasteinn_MpegDecoder__1plain_1strerror
  (JNIEnv * env, jclass, jint err);


#ifdef __cplusplus
}
#endif
#endif
